name: Release
"on":
  push:
    branches:
      - master
      - dev
      - beta

jobs:

  # dry-run to get next release version
  # using this plugin: https://github.com/felipecrs/semantic-release-export-data
  get-next-version:
    runs-on: ubuntu-latest
    # permission required for Semantic-Release step to push contents, even for dry-run
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx semantic-release --dry-run --no-ci
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
      - run: |
          echo "published: '${{ steps.get-next-version.outputs.new-release-published }}'"
          echo "release: '${{ steps.get-next-version.outputs.new-release-version }}'"
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
  
  # release using root package.json file for building release
  release:
    name: release
    runs-on: ubuntu-latest
    needs: get-next-version
    if: needs.get-next-version.outputs.new-release-published == 'true'
    # permission required for Semantic-Release step to push contents
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: |
          echo "The new release version is ${{ needs.get-next-version.outputs.new-release-version }}"
          echo "New release : ${{ steps.get-next-version.outputs.new-release-version }}" >> $GITHUB_STEP_SUMMARY
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
