# Test workflow
name: Test
on:
  push:
    branches:
      - variables

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:

  testShell:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - id: testJobShell
        run:  |
          if [[ "${BRANCH_NAME}" == "master" ]]; then 
            NPM_CONFIG_TAG='latest'
          elif [[ "${BRANCH_NAME}" == "beta" ]]; then 
            NPM_CONFIG_TAG='beta'
          else 
            NPM_CONFIG_TAG="${BRANCH_NAME}"
          fi

          # echo on workflow logs:
          echo "npm config TAG is ${NPM_CONFIG_TAG}"
          # display the workflow summary:
          echo "npm config TAG is ${NPM_CONFIG_TAG}" >> $GITHUB_STEP_SUMMARY
          # save env var for future jobs / steps:
          echo "NPM_CONFIG_TAG=${NPM_CONFIG_TAG}" >> "$GITHUB_OUTPUT"
    outputs:
      npm_config_tag: ${{ steps.testJobShell.outputs.NPM_CONFIG_TAG }}

  resultShell:
    runs-on: ubuntu-latest
    needs: testShell
    steps:
    - env:
        OUTPUT1: ${{ steps.testShell.outputs.npm_config_tag }}
      run: echo "output1 is '$OUTPUT1'"
    